= Applying RHEL updates to the bootc base images

We looked at how to add new software packages to a bootc host, but what about applying updates to packages in the base image? Using `dnf update` during a container build is not a good practice, and can lead to inconsistent images based on package visibility at build time.

Red Hat publishes updated base images to the Container Catalog regularly, to understand how to make the best use of them, we need to revisit tagging.

* Insert a screenshot of the dropdown in the catalog

== Anatomy of a container repository

Remember the naming convention for images is <registry>/<repository>/<name>:<tag>, so for the bootc images we have been using the registry is `registry.redhat.io` and the repository is `rhel9`. The table below describes the tags associated with the `rhel-bootc` image.
[cols="~,~"]
|===
|latest
|the most recent build of a major release

|9.5
|the most recent build of a minor release

|9.5-1742979700
|a timestamped build of a minor release
|===

So far, we have be using `registry.redhat.io/rhel9/rhel-bootc:9.5` in the FROM line of the Containerfile, meaning we are using the most recent build of the 9.5 minor release of the `rhel-bootc` image. 

At the time of writing that is also what `latest` would point to. Both of these also point to `9.5-1742979700`, as seen in the screenshot above.

Those timestamps are in UNIX epoch time so the `date` command can show us when a build was made.

....
date -d@1742979700
Wed Mar 26 05:01:40 AM EDT 2025
....
This also means that should a new build be published to the catalog, that new base image could be used depending on the state of the container image storage cache on the build host.

== Updating the base image using timestamps
Let's build a new image using an older code that still checks out to start.

[source,dockerfile,role="execute",subs=attributes+]
----
FROM registry.redhat.io/rhel9/rhel-bootc:9.5-1739946498

RUN dnf install -y httpd
RUN echo "Hello Red Hat" > /var/www/html/index.html

RUN systemctl enable httpd.service
----

Since we're using a tag that doesn't change in the registry, we know that we will always use the same base image no matter the state of the build host.

[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag {registry_hostname}/httpd
----


[source,bash,role="execute",subs=attributes+]
----
podman push {registry_hostname}/httpd
----

bootc switch on target VM

check some version of known RPm update

build with newer timestamp

[source,dockerfile,role="execute",subs=attributes+]
----
FROM registry.redhat.io/rhel9/rhel-bootc:9.5-1742979700

RUN dnf install -y httpd
RUN echo "Hello Red Hat" > /var/www/html/index.html

RUN systemctl enable httpd.service
----

Since we're using a tag that doesn't change in the registry, we know that we will always use the same base image no matter the state of the build host.

[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag {registry_hostname}/httpd
----
 Note we're using the same naming and tag for the image with our application in it. We want the host to see this as an update, not as a new image to switch into.

[source,bash,role="execute",subs=attributes+]
----
podman push {registry_hostname}/httpd
----

Making use of the tags in the catalog provides you with more options to control and trace your images. And to do the same with the packages you install, you can use something like Satellite to control the visibility of new packages at build time.